baseURL = 'https://alphasea.io/'
languageCode = 'en-us'
title = 'AlphaSea'
theme = "ananke"
relativeURLs = true
hasCJKLanguage = true

[menu]
[[menu.main]]
  name = 'AlphaSeaとは？'
  url = '/introduction'
  weight = -140
[[menu.main]]
  name = '仕組み'
  url = '/how-it-works'
  weight = -130
[[menu.main]]
  name = 'チュートリアル'
  url = '/tutorial'
  weight = -120
[[menu.main]]
  name = 'GitHub'
  url = 'https://github.com/alphasea-dapp'
  weight = -110
[[menu.main]]
  name = 'リーダーボード'
  url = 'https://app.alphasea.io'
  weight = -100
